### ISSUE TITLE
check usage of encodePacked vs encode (constant size)

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/honeybatcher#14]
via @pinkiebell

**Comment by TimDaub** [comment]
For e.g. <addr 0x, uint 0, uint 1> is the length when using abi.encodePacked same as <addr 0x, uint 1, uint 1> and <addr 0x, uint 0, uint 0> or are the 0 values removed? If so, it's important to use `encode`

**Comment by pinkiebell** [comment]
See: https://docs.soliditylang.org/en/latest/abi-spec.html#non-standard-packed-mode
This seems to be only important for dynamic sized types. 

```
types shorter than 32 bytes are neither zero padded nor sign extended and
dynamic types are encoded in-place and without the length.
array elements are padded, but still encoded in-place
```

So, they are actually 'padded' but the docs probably refer to the general solidity abi conventions - (values padded to evm word size).

**Comment by pinkiebell** [comment]
I'm dropping the lines  here too, for reference.

---
Here is a tip: if using encodePacked leads to <20 bytes, 20 bytes, 32 bytes > = 72 bytes in your case for keccak hashing then you are still charged for 3 words (96 bytes). The keccak hash functions operates on block with size 136. so 72 / 136 = 0,5294 filled with the rest zero padded and 96 / 136 = 0,7058 filled and the rest zeros.

You can be a bit more secure at the same cost 🙂

**Comment by TimDaub** [comment]
> This seems to be only important for dynamic sized types.

From the docs:

> In general, the encoding is ambiguous as soon as there are two dynamically-sized elements, because of the missing length field.

> Here is a tip: if using encodePacked leads to <20 bytes, 20 bytes, 32 bytes > = 72 bytes in your case for keccak hashing then you are still charged for 3 words (96 bytes). The keccak hash functions operates on block with size 136. so 72 / 136 = 0,5294 filled with the rest zero padded and 96 / 136 = 0,7058 filled and the rest zeros.
> 
> You can be a bit more secure at the same cost 🙂

I understand this, but where do you see the security issue? Is it that in case we use `encodePacked` and that e.g. I forget and start encoding dynamically-sized types, that the rollup may generate ambiguous root hashes?

**Comment by pinkiebell** [comment]
> > This seems to be only important for dynamic sized types.
> 
> From the docs:
> 
> > In general, the encoding is ambiguous as soon as there are two dynamically-sized elements, because of the missing length field.
> 
> > Here is a tip: if using encodePacked leads to <20 bytes, 20 bytes, 32 bytes > = 72 bytes in your case for keccak hashing then you are still charged for 3 words (96 bytes). The keccak hash functions operates on block with size 136. so 72 / 136 = 0,5294 filled with the rest zero padded and 96 / 136 = 0,7058 filled and the rest zeros.
> > You can be a bit more secure at the same cost 🙂
> 
> I understand this, but where do you see the security issue? Is it that in case we use `encodePacked` and that e.g. I forget and start encoding dynamically-sized types, that the rollup may generate ambiguous root hashes?

It's not a 'issue', but you end up with the same cost (might be even actually cheaper) and give the hash function a bit more entropy.
